version: "3"

services:
  postgres:
    image: library/postgres:13-alpine
    environment:
      POSTGRES_DB: shortify
      POSTGRES_USER: shortify_dba
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: library/redis:5-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  postgres: {}
  redis: {}